package dev.yidafu.surpass.UserCenter.dao;

import dev.yidafu.surpass.UserCenter.entity.Authentications;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface AuthenticationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentications
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentications
     *
     * @mbg.generated
     */
    int insert(Authentications record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentications
     *
     * @mbg.generated
     */
    Authentications selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentications
     *
     * @mbg.generated
     */
    List<Authentications> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentications
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Authentications record);
}