package dev.yidafu.feoj.UserCenter.dao;

import dev.yidafu.feoj.UserCenter.entity.RegisterLogs;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface RegisterLogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    int insert(RegisterLogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    RegisterLogs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    List<RegisterLogs> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RegisterLogs record);
}