server:
  port: 3001
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/oj_user?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC'
    username: 'root'
    password: '123456'
    driver-class-name: 'com.mysql.cj.jdbc.Driver'
#    schema: "classpath:/resources/sql/user.sql"
#    data: "classpath:/resources/sql/data.sql"

#mybatis配置
mybatis:
  #映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #模型所在的保命
  type-aliases-package: dev.yidafu.UserCenter.entity

# https://docs.spring.io/spring-boot/docs/1.5.3.RELEASE/reference/html/production-ready-endpoints.html#production-ready-endpoint-cors
#endpoints:
#  cors:
#    allow-credentials: true 
#    allowed-headers: "*"
#    allowed-methods:
#      - GET
#      - POST
#      - DELETE
#    allowed-origins: "http://localhost:3000"