package dev.yidafu.surpass.UserCenter.entity;

import java.io.Serializable;

public class Authentications implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentications.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentications.userId
     *
     * @mbg.generated
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentications.appType
     *
     * @mbg.generated
     */
    private Integer appType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentications.appUserId
     *
     * @mbg.generated
     */
    private String appUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column authentications.accessToken
     *
     * @mbg.generated
     */
    private String accessToken;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table authentications
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentications.id
     *
     * @return the value of authentications.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentications.id
     *
     * @param id the value for authentications.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentications.userId
     *
     * @return the value of authentications.userId
     *
     * @mbg.generated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentications.userId
     *
     * @param userId the value for authentications.userId
     *
     * @mbg.generated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentications.appType
     *
     * @return the value of authentications.appType
     *
     * @mbg.generated
     */
    public Integer getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentications.appType
     *
     * @param appType the value for authentications.appType
     *
     * @mbg.generated
     */
    public void setAppType(Integer appType) {
        this.appType = appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentications.appUserId
     *
     * @return the value of authentications.appUserId
     *
     * @mbg.generated
     */
    public String getAppUserId() {
        return appUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentications.appUserId
     *
     * @param appUserId the value for authentications.appUserId
     *
     * @mbg.generated
     */
    public void setAppUserId(String appUserId) {
        this.appUserId = appUserId == null ? null : appUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column authentications.accessToken
     *
     * @return the value of authentications.accessToken
     *
     * @mbg.generated
     */
    public String getAccessToken() {
        return accessToken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column authentications.accessToken
     *
     * @param accessToken the value for authentications.accessToken
     *
     * @mbg.generated
     */
    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken == null ? null : accessToken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table authentications
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", appType=").append(appType);
        sb.append(", appUserId=").append(appUserId);
        sb.append(", accessToken=").append(accessToken);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}