package dev.yidafu.auncel.UserCenter.entity;

import java.io.Serializable;
import java.util.Date;

public class RegisterLogs implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_logs.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_logs.registerTime
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_logs.registerTp
     *
     * @mbg.generated
     */
    private String registerTp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column register_logs.message
     *
     * @mbg.generated
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_logs.id
     *
     * @return the value of register_logs.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_logs.id
     *
     * @param id the value for register_logs.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_logs.registerTime
     *
     * @return the value of register_logs.registerTime
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_logs.registerTime
     *
     * @param registerTime the value for register_logs.registerTime
     *
     * @mbg.generated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_logs.registerTp
     *
     * @return the value of register_logs.registerTp
     *
     * @mbg.generated
     */
    public String getRegisterTp() {
        return registerTp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_logs.registerTp
     *
     * @param registerTp the value for register_logs.registerTp
     *
     * @mbg.generated
     */
    public void setRegisterTp(String registerTp) {
        this.registerTp = registerTp == null ? null : registerTp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column register_logs.message
     *
     * @return the value of register_logs.message
     *
     * @mbg.generated
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column register_logs.message
     *
     * @param message the value for register_logs.message
     *
     * @mbg.generated
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table register_logs
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", registerTp=").append(registerTp);
        sb.append(", message=").append(message);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}